In [1]:
%cd ..

/Users/martinbierey/git/dax-hoc

In [2]:
from src.db import read_news
from IPython.display import display,HTML
import pandas as pd 
#pd.set_option('display.max_colwidth', None)

In [3]:
df = read_news()

In [6]:
i = 0 
df['headline'].iloc[i],

('Eckert & Ziegler Secures Patient Access to Critical Eye Cancer Treatment with MDR Certification for Ru-106 Eye Applicators',
 'EN\nEnglish\nGerman\nShare\nPrint\nLanguage\nEnglish\nGerman\nCompany info\nCompany info\nISIN\nDE0005659700\nCountry\nDeutschland\nCorporate | 10 April 2026 10:00\nEckert & Ziegler SE\nEckert & Ziegler Secures Patient Access to Critical Eye Cancer Treatment with MDR Certification for Ru-106 Eye Applicators\nEckert & Ziegler SE\n/ Key word(s): Regulatory Approval\nEckert & Ziegler Secures Patient Access to Critical Eye Cancer Treatment with MDR Certification for Ru-106 Eye Applicators\n10.04.2026 / 10:00 CET/CEST\nThe issuer is solely responsible for the content of this announcement.\nBerlin, 10 April 2026. Eckert & Ziegler BEBIG GmbH, subsidiary of Eckert & Ziegler SE with focus on brachytherapy solutions for the treatment of eye tumors and prostate cancer, obtained the MDR certificate for its Ruthenium-106 (Ru-106) Eye Applicators from competent authorities. Eckert & Ziegler is the only global provider of these eye applicators. Therefore, this important milestone is a critical safeguard against treatment shortages.\nThe Medical Device Regulation (MDR) is a European Union directive (EU 2017/745) with the aim of improving the quality of medical devices and increasing patient safety. Obtaining this certification guarantees the long-term availability of Ru-106 Eye Applicators within the EU. These medical devices have been manufactured and internationally marketed by Eckert & Ziegler for more than 30 years. They are actively used in almost 50 countries and contribute several million euros in annual sales to the Eckert & Ziegler Group’s earnings.\nDuring an ophthalmic brachytherapy procedure, a small radioactive plaque containing Ru-106 is used to treat uveal melanoma in adults or retinoblastoma in children. The plaque is sutured to the wall of the eye, adjacent to the tumor, and left in place for several days until the required dose of radiation has been delivered.\xa0As an alternative to the removal of the affected eye, this treatment offers a chance for patients to conserve vision and quality of life.\n“The dedication of our team to achieve MDR certification for a niche product like the Ru-106 Eye Applicators demonstrates our commitment to ensure the long-term availability of this vital form of therapy to treatment centers and patients,” explained Katrin Antonenko, Managing Director of Eckert & Ziegler BEBIG GmbH. “The milestone furthermore marks the durable legacy of a product that started to pave the way for the sustainable and successful growth of the Eckert & Ziegler Group more than three decades ago. The experience gained during the successful approval process is expected to expedite additional projects.”\nAbout Eckert & Ziegler\nEckert & Ziegler SE, with more than 1,000 employees, is a leading specialist in isotope-related components for nuclear medicine and radiation therapy. The company offers a broad range of services and products for the radiopharmaceutical industry, from early development work to contract manufacturing and distribution. Eckert & Ziegler shares (ISIN DE0005659700) are listed in the TecDAX index of Deutsche Börse.\nContributing to saving lives.\nContact\nEckert & Ziegler SE\nRobert-Rössle-Str. 10, 13125 Berlin, Germany\nJan Schöpflin, Marketing / Karolin Riehle, Investor Relations\njan.schoepflin@ezag.de\n/\nkarolin.riehle@ezag.de\nTel.: +49 (0) 30 / 94 10 84-138;\nwww.ezag.com\n10.04.2026 CET/CEST Dissemination of a Corporate News, transmitted by\nEQS News\n– a service of\nEQS Group\n.\nThe issuer is solely responsible for the content of this announcement.\nThe EQS Distribution Services include Regulatory Announcements, Financial/Corporate News and Press Releases.\nLanguage:\nEnglish\nCompany:\nEckert & Ziegler SE\nRobert-Rössle-Str.10\n13125 Berlin\nGermany\nPhone:\n+49 30 941084-138\nFax:\n+49 30 941084-0\nInternet:\nwww.ezag.de\nISIN:\nDE0005659700\nWKN:\n565970\nIndices:\nSDAX, TecDax,\nListed:\nRegulated Market in Frankfurt (Prime Standard); Regulated Unofficial Market in Dusseldorf, Hamburg, Munich, Stuttgart, Tradegate BSX\nEQS News ID:\n2306166\nEnd of News\nEQS News Service\n2306166\xa0\xa010.04.2026\xa0CET/CEST\nLatest News\nNews Functions\n\ue68d\nAdd to favorite list\nRemove from favorites\nAdditional Functions\n\ue910\nAdd to watchlist\n\ue60c\nShow Company Info\n\ue7fa\nShare price chart\n10 April 2026\n10:00\nCorporate\nEckert & Ziegler SE\nCorporate\nEckert & Ziegler Secures Patient Access to Critical Eye Cancer Treatment with MDR Certification for Ru-106 Eye Applicators\n\ue90f\n27 March 2026\n09:00\nResearch\nEckert & Ziegler SE\nResearch\nOriginal-Research: Eckert & Ziegler SE (von NuWays AG): BUY\n\ue90f\n26 March 2026\n07:45\nCorporate\nEckert & Ziegler SE\nCorporate\nEckert & Ziegler: Strong FY 2025 with Positive Outlook\n\ue90f\n24 March 2026\n10:18\nDirectors’ Dealings\nEckert & Ziegler SE\nDirectors’ Dealings\nEckert & Ziegler SE: Dr. Gunnar Mann, Allocation of 12,545 shares as part of executive board remuneration (own shares of the issuer). This is a share-based remuneration with an automatic allocation.\n\ue90f\n10:05\nDirectors’ Dealings\nEckert & Ziegler SE\nDirectors’ Dealings\nEckert & Ziegler SE: Dr. Harald Hasselmann, Allocation of 62,541 shares as part of executive board remuneration (own shares of the issuer). This is a share-based remuneration with an automatic allocation.\n\ue90f\nMore News\nLatest Reports\nNews Functions\n\ue68d\nAdd to favorite list\nRemove from favorites\nAdditional Functions\n\ue910\nAdd to watchlist\n\ue60c\nShow Company Info\n\ue7fa\nShare price chart\n13 November 2025\nQuarterly Report\nPDF\nEckert & Ziegler SE\nQuarterly Report\nPDF\nQ3 statement / Q3 financial report 2025\n\ue90f\n28 August 2025\nQuarterly Report\nPDF\nEckert & Ziegler SE\nQuarterly Report\nPDF\nHalf-yearly financial report 2025\n\ue90f\n13 May 2025\nQuarterly Report\nPDF\nEckert & Ziegler SE\nQuarterly Report\nPDF\nQ1 statement / Q1 financial report 2025\n\ue90f\n28 April 2025\nAnnual Report\nPDF\nEckert & Ziegler SE\nAnnual Report\nPDF\nAnnual financial report 2024 (PDF)\n\ue90f\nAnnual Report\nPDF\nEckert & Ziegler SE\nAnnual Report\nPDF\nAnnual financial report 2024 (PDF)\n\ue90f\nMore Reports\nUpcoming Events\nEvent Functions\n\ue68d\nAdd to favorite list\nRemove from favorites\nAdditional Functions\n\ue910\nAdd to watchlist\n\ue60c\nShow Company Info\n\ue7fa\nShare price chart\n12\nMay 26\nEckert & Ziegler SE\nPublication Quarterly Financial Report (call-date Q1)\n24\nJun 26\nEckert & Ziegler SE\nAnnual General Meeting\n13\nAug 26\nEckert & Ziegler SE\nPublication Half-yearly Financial Report\n12\nNov 26\nEckert & Ziegler SE\nPublication Quarterly Financial Report (call-date Q3)\nMore Events\nWebcasts\nNo Webcasts found')

In [7]:
print(df['content'].iloc[i])

EN
English
German
Share
Print
Language
English
German
Company info
Company info
ISIN
DE0005659700
Country
Deutschland
Corporate | 10 April 2026 10:00
Eckert & Ziegler SE
Eckert & Ziegler Secures Patient Access to Critical Eye Cancer Treatment with MDR Certification for Ru-106 Eye Applicators
Eckert & Ziegler SE
/ Key word(s): Regulatory Approval
Eckert & Ziegler Secures Patient Access to Critical Eye Cancer Treatment with MDR Certification for Ru-106 Eye Applicators
10.04.2026 / 10:00 CET/CEST
The issuer is solely responsible for the content of this announcement.
Berlin, 10 April 2026. Eckert & Ziegler BEBIG GmbH, subsidiary of Eckert & Ziegler SE with focus on brachytherapy solutions for the treatment of eye tumors and prostate cancer, obtained the MDR certificate for its Ruthenium-106 (Ru-106) Eye Applicators from competent authorities. Eckert & Ziegler is the only global provider of these eye applicators. Therefore, this important milestone is a critical safeguard against treatment shortages.
The Medical Device Regulation (MDR) is a European Union directive (EU 2017/745) with the aim of improving the quality of medical devices and increasing patient safety. Obtaining this certification guarantees the long-term availability of Ru-106 Eye Applicators within the EU. These medical devices have been manufactured and internationally marketed by Eckert & Ziegler for more than 30 years. They are actively used in almost 50 countries and contribute several million euros in annual sales to the Eckert & Ziegler Group’s earnings.
During an ophthalmic brachytherapy procedure, a small radioactive plaque containing Ru-106 is used to treat uveal melanoma in adults or retinoblastoma in children. The plaque is sutured to the wall of the eye, adjacent to the tumor, and left in place for several days until the required dose of radiation has been delivered. As an alternative to the removal of the affected eye, this treatment offers a chance for patients to conserve vision and quality of life.
“The dedication of our team to achieve MDR certification for a niche product like the Ru-106 Eye Applicators demonstrates our commitment to ensure the long-term availability of this vital form of therapy to treatment centers and patients,” explained Katrin Antonenko, Managing Director of Eckert & Ziegler BEBIG GmbH. “The milestone furthermore marks the durable legacy of a product that started to pave the way for the sustainable and successful growth of the Eckert & Ziegler Group more than three decades ago. The experience gained during the successful approval process is expected to expedite additional projects.”
About Eckert & Ziegler
Eckert & Ziegler SE, with more than 1,000 employees, is a leading specialist in isotope-related components for nuclear medicine and radiation therapy. The company offers a broad range of services and products for the radiopharmaceutical industry, from early development work to contract manufacturing and distribution. Eckert & Ziegler shares (ISIN DE0005659700) are listed in the TecDAX index of Deutsche Börse.
Contributing to saving lives.
Contact
Eckert & Ziegler SE
Robert-Rössle-Str. 10, 13125 Berlin, Germany
Jan Schöpflin, Marketing / Karolin Riehle, Investor Relations
jan.schoepflin@ezag.de
/
karolin.riehle@ezag.de
Tel.: +49 (0) 30 / 94 10 84-138;
www.ezag.com
10.04.2026 CET/CEST Dissemination of a Corporate News, transmitted by
EQS News
– a service of
EQS Group
.
The issuer is solely responsible for the content of this announcement.
The EQS Distribution Services include Regulatory Announcements, Financial/Corporate News and Press Releases.
Language:
English
Company:
Eckert & Ziegler SE
Robert-Rössle-Str.10
13125 Berlin
Germany
Phone:
+49 30 941084-138
Fax:
+49 30 941084-0
Internet:
www.ezag.de
ISIN:
DE0005659700
WKN:
565970
Indices:
SDAX, TecDax,
Listed:
Regulated Market in Frankfurt (Prime Standard); Regulated Unofficial Market in Dusseldorf, Hamburg, Munich, Stuttgart, Tradegate BSX
EQS News ID:
2306166
End of News
EQS News Service
2306166  10.04.2026 CET/CEST
Latest News
News Functions

Add to favorite list
Remove from favorites
Additional Functions

Add to watchlist

Show Company Info

Share price chart
10 April 2026
10:00
Corporate
Eckert & Ziegler SE
Corporate
Eckert & Ziegler Secures Patient Access to Critical Eye Cancer Treatment with MDR Certification for Ru-106 Eye Applicators

27 March 2026
09:00
Research
Eckert & Ziegler SE
Research
Original-Research: Eckert & Ziegler SE (von NuWays AG): BUY

26 March 2026
07:45
Corporate
Eckert & Ziegler SE
Corporate
Eckert & Ziegler: Strong FY 2025 with Positive Outlook

24 March 2026
10:18
Directors’ Dealings
Eckert & Ziegler SE
Directors’ Dealings
Eckert & Ziegler SE: Dr. Gunnar Mann, Allocation of 12,545 shares as part of executive board remuneration (own shares of the issuer). This is a share-based remuneration with an automatic allocation.

10:05
Directors’ Dealings
Eckert & Ziegler SE
Directors’ Dealings
Eckert & Ziegler SE: Dr. Harald Hasselmann, Allocation of 62,541 shares as part of executive board remuneration (own shares of the issuer). This is a share-based remuneration with an automatic allocation.

More News
Latest Reports
News Functions

Add to favorite list
Remove from favorites
Additional Functions

Add to watchlist

Show Company Info

Share price chart
13 November 2025
Quarterly Report
PDF
Eckert & Ziegler SE
Quarterly Report
PDF
Q3 statement / Q3 financial report 2025

28 August 2025
Quarterly Report
PDF
Eckert & Ziegler SE
Quarterly Report
PDF
Half-yearly financial report 2025

13 May 2025
Quarterly Report
PDF
Eckert & Ziegler SE
Quarterly Report
PDF
Q1 statement / Q1 financial report 2025

28 April 2025
Annual Report
PDF
Eckert & Ziegler SE
Annual Report
PDF
Annual financial report 2024 (PDF)

Annual Report
PDF
Eckert & Ziegler SE
Annual Report
PDF
Annual financial report 2024 (PDF)

More Reports
Upcoming Events
Event Functions

Add to favorite list
Remove from favorites
Additional Functions

Add to watchlist

Show Company Info

Share price chart
12
May 26
Eckert & Ziegler SE
Publication Quarterly Financial Report (call-date Q1)
24
Jun 26
Eckert & Ziegler SE
Annual General Meeting
13
Aug 26
Eckert & Ziegler SE
Publication Half-yearly Financial Report
12
Nov 26
Eckert & Ziegler SE
Publication Quarterly Financial Report (call-date Q3)
More Events
Webcasts
No Webcasts found

In [ ]:
df[

In [4]:
df.sort_values('created_at',ascending=False)

,id,created_at,created_at_utc,category,category_code,company_name,company_uuid,isin,headline,language,locale,timezone,content,share_url,fetched_at,raw_json
0,aed9603c-c357-4d5d-8e02-23fb144df2d5_en,2026-04-10 10:00:03.000000,2026-04-10 08:00:03.000000,Corporate,corporate,Eckert & Ziegler SE,5b6e4698-ea7c-11e8-902f-2c44fd856d8c,DE0005659700,Eckert & Ziegler Secures Patient Access to Cri...,en,"en,de",Europe/Berlin,EN\nEnglish\nGerman\nShare\nPrint\nLanguage\nE...,https://www.eqs-news.com/news/corporate/eckert...,2026-04-10 08:12:18.227945,"{""id"": ""aed9603c-c357-4d5d-8e02-23fb144df2d5_e..."
1,8fa7180e-d5cd-4d9a-935c-3aeb31502cce_en,2026-04-10 09:05:43.000000,2026-04-10 07:05:43.000000,Corporate,corporate,MCS Market Communication Service GmbH,a9623a42-9180-1014-b986-960408a810f2,noisin061604,Redwood AI kündigt aktualisierte Cloud-basiert...,de,de,Europe/Berlin,DE\nGerman\nShare\nPrint\nLanguage\nGerman\nCo...,https://www.eqs-news.com/news/corporate/redwoo...,2026-04-10 08:12:18.228063,"{""id"": ""8fa7180e-d5cd-4d9a-935c-3aeb31502cce_e..."
2,2bbdb741-e951-4768-885f-86803ebbcf52_en,2026-04-10 09:05:04.000000,2026-04-10 07:05:04.000000,Corporate,corporate,Lenzing AG,c6dbd2be-a1b9-1014-842b-fc2c6b498e93,AT0000644505,Award‑Nominated LENZING™ DualWipe Supports Eur...,en,"en,de",Europe/Berlin,EN\nEnglish\nGerman\nShare\nPrint\nLanguage\nE...,https://www.eqs-news.com/news/corporate/awarde...,2026-04-10 08:12:18.228105,"{""id"": ""2bbdb741-e951-4768-885f-86803ebbcf52_e..."
3,ec0d2028-3ee1-4dda-a691-235d4aad9a8b_en,2026-04-10 09:00:04.000000,2026-04-10 07:00:04.000000,Corporate,corporate,Dr. Ing. h.c. F. Porsche AG,a147e736-98b8-1014-aad5-e51d0155c5b4,DE000PAG9113,Expected decline in sales due to limited produ...,en,"en,de",Europe/Berlin,EN\nEnglish\nGerman\nShare\nPrint\nLanguage\nE...,https://www.eqs-news.com/news/corporate/expect...,2026-04-10 08:12:18.228134,"{""id"": ""ec0d2028-3ee1-4dda-a691-235d4aad9a8b_e..."
4,df82b92d-d912-4604-bd48-d4706a16a107_en,2026-04-10 08:59:23.000000,2026-04-10 06:59:23.000000,Corporate,corporate,Verbund AG,5b7eeb50-ea7c-11e8-902f-2c44fd856d8c,AT0000746409,VERBUND AG: VERBUND successfully places EUR 70...,en,"de,en",Europe/Berlin,EN\nGerman\nEnglish\nShare\nPrint\nLanguage\nG...,https://www.eqs-news.com/news/corporate/verbun...,2026-04-10 08:12:18.228158,"{""id"": ""df82b92d-d912-4604-bd48-d4706a16a107_e..."
5,4ba52f6c-b4d7-4803-99ba-a723aa81b8c3_en,2026-04-10 07:30:04.000000,2026-04-10 05:30:04.000000,Corporate,corporate,Nordex SE,5b73f7aa-ea7c-11e8-902f-2c44fd856d8c,DE000A0D6554,Nordex Group lands 80 MW contract in Spain,en,"en,de",Europe/Berlin,EN\nEnglish\nGerman\nShare\nPrint\nLanguage\nE...,https://www.eqs-news.com/news/corporate/nordex...,2026-04-10 08:12:18.228182,"{""id"": ""4ba52f6c-b4d7-4803-99ba-a723aa81b8c3_e..."
6,e2e25e0a-39df-4a1a-8327-2b2d7bdc7de0_en,2026-04-10 07:00:13.000000,2026-04-10 05:00:13.000000,Corporate,corporate,Chocoladefabriken Lindt & Sprüngli AG,5b73e32d-ea7c-11e8-902f-2c44fd856d8c,CH0010570759,Lindt & Sprüngli completes buyback of own shar...,en,"de,en",Europe/Berlin,EN\nGerman\nEnglish\nShare\nPrint\nLanguage\nG...,https://www.eqs-news.com/news/corporate/lindt-...,2026-04-10 08:12:18.228204,"{""id"": ""e2e25e0a-39df-4a1a-8327-2b2d7bdc7de0_e..."
7,8451abc6-073b-427b-a140-c3acfbcb5f91_en,2026-04-10 06:25:22.000000,2026-04-10 04:25:22.000000,Corporate,corporate,METLEN Energy & Metals PLC,3b3b1294-33f3-11f1-b496-8ee8dada2dd9,noisin465144,METLEN Energy &amp; Metals: Geschäftsergebniss...,de,de,Europe/Berlin,DE\nGerman\nShare\nPrint\nLanguage\nGerman\nCo...,https://www.eqs-news.com/news/corporate/metlen...,2026-04-10 08:12:18.228226,"{""id"": ""8451abc6-073b-427b-a140-c3acfbcb5f91_e..."
8,84809165-4515-4e94-a62a-f439d72759d1_en,2026-04-10 06:00:00.000000,2026-04-10 04:00:00.000000,Ad-hoc,adhoc,Bossard Holding AG,7ae7e0d7-53f9-1016-a45b-6f6105d60f5f,CH0238627142,Sales for the first quarter 2026,en,"de,en",Europe/Zurich,EN\nGerman\nEnglish\nShare\nPrint\nLanguage\nG...,https://www.eqs-news.com/news/ad-hoc/sales-for...,2026-04-10 08:12:18.228247,"{""id"": ""84809165-4515-4e94-a62a-f439d72759d1_e..."
9,bd9d8d42-1d31-423d-bdb3-31b679f10c9a_en,2026-04-09 22:00:00.000000,2026-04-09 20:00:00.000000,Corporate,corporate,VAT Group AG,5c28f07e-ea7c-11e8-902f-2c44fd856d8c,CH0311864901,Invitation - First Quarter 2026 Trading Update...,en,"de,en",Europe/Zurich,EN\nGerman\nEnglish\nShare\nPrint\nLanguage\nG...,https://www.eqs-news.com/news/corporate/invita...,2026-04-10 08:12:18.228269,"{""id"": ""bd9d8d42-1d31-423d-bdb3-31b679f10c9a_e..."
10,59c70329-832e-4e6a-bca4-ab2137d3f8bf_en,2026-04-09 20:05:03.000000,2026-04-09 18:05:03.000000,AGM announcements,AGM,Raiffeisen Bank International AG,5b7e332d-ea7c-11e8-902f-2c44fd856d8c,AT0000606306,Raiffeisen Bank International AG: Resolution o...,en,"en,de",Europe/Berlin,EN\nEnglish\nGerman\nShare\nPrint\nLanguage\nE...,https://www.eqs-news.com/news/agm-announcement...,2026-04-10 08:12:18.228290,"{""id"": ""59c70329-832e-4e6a-bca4-ab2137d3f8bf_e..."
11,e875c460-cb2e-424c-a20d-497834e1ded3_en,2026-04-09 16:20:32.000000,2026-04-09 14:20:32.000000,Corporate,corporate,Phygital International,377aa9ba-991d-11f0-ad23-cfb683a657f9,noisin685643,Bewerbungen der Gastgeberstadt für die Games o...,de,de,Europe/Berlin,DE\nGerman\nShare\nPrint\nLanguage\nGerman\nCo...,https://www.eqs-news.com/news/corporate/bewerb...,2026-04-09 14:21:44.810086,"{""id"": ""e875c460-cb2e-424c-a20d-497834e1ded3_e..."
12,c7829ac5-0376-4798-a2a2-3f5dfc1c7486_en,2026-04-09 16:10:22.000000,2026-04-09 14:10:22.000000,Corporate,corporate,Phemex,4e20b658-a6b2-11f0-a057-f687cc42c8b9,noisin761735,Der Handel mit Rohöl bei Phemex TradFi steigt ...,de,de,Europe/Berlin,DE\nGerman\nShare\nPrint\nLanguage\nGerman\nCo...,https://www.eqs-news.com/news/corporate/der-ha...,2026-04-09 14:12:25.995963,"{""id"": ""c7829ac5-0376-4798-a2a2-3f5dfc1c7486_e..."
13,ef20e547-fe6c-4123-8b72-c64fe6dfb55c_en,2026-04-09 16:09:07.000000,2026-04-09 14:09:07.000000,Directors' Dealings,dd,All for One Group SE,5b75e76f-ea7c-11e8-902f-2c44fd856d8c,DE0005110001,All for One Group SE: Knünz Invest Beteiligung...,en,"de,en",Europe/Berlin,EN\nGerman\nEnglish\nShare\nPrint\nLanguage\nG...,https://www.eqs-news.com/news/directors-dealin...,2026-04-09 14:09:24.338082,"{""id"": ""ef20e547-fe6c-4123-8b72-c64fe6dfb55c_e..."
14,2780afe3-6c25-4e3e-a654-c99688183342_en,2026-04-09 16:08:03.000000,2026-04-09 14:08:03.000000,Advance financial reports,AFR,Dierig Holding AG,5b77905f-ea7c-11e8-902f-2c44fd856d8c,DE0005580005,Dierig Holding AG: Preliminary announcement of...,en,"de,en",Europe/Berlin,EN\nGerman\nEnglish\nShare\nPrint\nLanguage\nG...,https://www.eqs-news.com/news/advance-financia...,2026-04-09 14:09:24.338204,"{""id"": ""2780afe3-6c25-4e3e-a654-c99688183342_e..."
15,e3615664-b916-44e3-88fb-81f9c657bea6_en,2026-04-09 16:00:03.000000,2026-04-09 14:00:03.000000,Advance financial reports,AFR,Leonteq Securities AG,5c275639-ea7c-11e8-902f-2c44fd856d8c,CH0266685855,Leonteq Securities AG: Preliminary announcemen...,en,"de,en",Europe/Berlin,EN\nGerman\nEnglish\nShare\nPrint\nLanguage\nG...,https://www.eqs-news.com/news/advance-financia...,2026-04-09 14:04:22.377956,"{""id"": ""e3615664-b916-44e3-88fb-81f9c657bea6_e..."
16,d9c8f8df-6b87-4ae7-acd1-02412f83366c_en,2026-04-09 16:00:03.000000,2026-04-09 14:00:03.000000,Voting rights,PVR,Wienerberger AG,5b734cc3-ea7c-11e8-902f-2c44fd856d8c,AT0000831706,Wienerberger AG: Release according to Article ...,en,"en,de",Europe/Berlin,EN\nEnglish\nGerman\nShare\nPrint\nLanguage\nE...,https://www.eqs-news.com/news/voting-rights/wi...,2026-04-09 14:04:22.378081,"{""id"": ""d9c8f8df-6b87-4ae7-acd1-02412f83366c_e..."
17,ebf44130-2e08-44ae-9a9b-f4944085091a_en,2026-04-09 15:45:22.000000,2026-04-09 13:45:22.000000,Corporate,corporate,Abilitie,933a49f2-3352-11f1-a7ea-cad8cccd6c35,noisin343368,"Abilitie, TED und St. Edward's University star...",de,de,Europe/Berlin,DE\nGerman\nShare\nPrint\nLanguage\nGerman\nCo...,https://www.eqs-news.com/news/corporate/abilit...,2026-04-09 13:46:16.917224,"{""id"": ""ebf44130-2e08-44ae-9a9b-f4944085091a_e..."
18,308bb42c-2e3b-45bc-86da-5216acb9cf07_en,2026-04-09 15:40:22.000000,2026-04-09 13:40:22.000000,Corporate,corporate,AMPERA,24890aee-3392-11f1-b13e-cbf643a9783c,noisin654808,AMPERA eröffnet offiziell den weltweiten Haupt...,de,de,Europe/Berlin,DE\nGerman\nShare\nPrint\nLanguage\nGerman\nCo...,https://www.eqs-news.com/news/corporate/ampera...,2026-04-09 13:42:19.840336,"{""id"": ""308bb42c-2e3b-45bc-86da-5216acb9cf07_e..."
19,5a076952-fee2-4bb1-a3e5-2c6af6663c63_en,2026-04-09 15:39:03.000000,2026-04-09 13:39:03.000000,Corporate,corporate,InnoTec TSS AG,5b7d1dd0-ea7c-11e8-902f-2c44fd856d8c,DE0005405104,InnoTec TSS AG gibt vorläufige Geschäftszahlen...,de,de,Europe/Berlin,DE\nGerman\nShare\nPrint\nLanguage\nGerman\nCo...,https://www.eqs-news.com/news/corporate/innote...,2026-04-09 13:40:19.314949,"{""id"": ""5a076952-fee2-4bb1-a3e5-2c6af6663c63_e..."
20,b3a7b790-7131-4073-a0ff-de7073456543_en,2026-04-09 15:30:05.000000,2026-04-09 13:30:05.000000,UK Regulatory,UK-Regulatory,Commerzbank Aktiengesellschaft,5b6e7203-ea7c-11e8-902f-2c44fd856d8c,DE000CBK1001,Invitation to the Annual General Meeting of Co...,en,en,Europe/Berlin,EN\nEnglish\nShare\nPrint\nLanguage\nEnglish\n...,https://www.eqs-news.com/news/uk-regulatory/in...,2026-04-09 13:35:45.017422,"{""id"": ""b3a7b790-7131-4073-a0ff-de7073456543_e..."
21,83b6a0b8-6c3e-41d5-9f94-f021eeae6411_en,2026-04-09 15:26:13.000000,2026-04-09 13:26:13.000000,Corporate,corporate,Commerzbank Aktiengesellschaft,5b6e7203-ea7c-11e8-902f-2c44fd856d8c,DE000CBK1001,Invitation to the Annual General Meeting of Co...,en,"de,en",Europe/Berlin,EN\nGerman\nEnglish\nShare\nPrint\nLanguage\nG...,https://www.eqs-news.com/news/corporate/invita...,2026-04-09 13:35:45.017526,"{""id"": ""83b6a0b8-6c3e-41d5-9f94-f021eeae6411_e..."
22,f05e7086-d878-414f-93ec-48112310cc1a_en,2026-04-09 15:20:22.000000,2026-04-09 13:20:22.000000,Corporate,corporate,Phygital International,377aa9ba-991d-11f0-ad23-cfb683a657f9,noisin685643,Host City Bids Open for The Games Of The Futur...,en,en,Europe/Berlin,EN\nEnglish\nShare\nPrint\nLanguage\nEnglish\n...,https://www.eqs-news.com/news/corporate/host-c...,2026-04-09 13:35:45.017568,"{""id"": ""f05e7086-d878-414f-93ec-48112310cc1a_e..."
23,b97aa476-01fb-4483-8a75-917af30183f6_en,2026-04-09 15:11:33.000000,2026-04-09 13:11:33.000000,Corporate,corporate,Vonovia SE,5bf8f933-ea7c-11e8-902f-2c44fd856d8c,DE000A1ML7J1,Dr Anne-Marie Großmann-Minkwitz nominated for ...,en,"de,en",Europe/Berlin,EN\nGerman\nEnglish\nShare\nPrint\nLanguage\nG...,https://www.eqs-news.com/news/corporate/dr-ann...,2026-04-09 13:35:45.017596,"{""id"": ""b97aa476-01fb-4483-8a75-917af30183f6_e..."
24,4bd0ceb1-ecdb-420f-8a92-870ec4b34a56_en,2026-04-09 15:05:35.000000,2026-04-09 13:05:35.000000,AGM announcements,AGM,Jungheinrich AG,5b716a4c-ea7c-11e8-902f-2c44fd856d8c,DE0006219934,Jungheinrich Aktiengesellschaft: Bekanntmachun...,de,de,Europe/Berlin,DE\nGerman\nShare\nPrint\nLanguage\nGerman\nCo...,https://www.eqs-news.com/news/agm-announcement...,2026-04-09 13:35:45.017621,"{""id"": ""4bd0ceb1-ecdb-420f-8a92-870ec4b34a56_e..."
25,f8511373-a125-420f-9a28-629c767cb97e_en,2026-04-09 15:05:34.000000,2026-04-09 13:05:34.000000,AGM announcements,AGM,init innovation in traffic systems SE,5b7921eb-ea7c-11e8-902f-2c44fd856d8c,DE0005759807,init innovation in traffic systems SE: Bekannt...,de,de,Europe/Berlin,DE\nGerman\nShare\nPrint\nLanguage\nGerman\nCo...,https://www.eqs-news.com/news/agm-announcement...,2026-04-09 13:35:45.017646,"{""id"": ""f8511373-a125-420f-9a28-629c767cb97e_e..."
26,e0dcf63f-e89e-4c13-b580-8eda9fc6910f_en,2026-04-09 15:05:34.000000,2026-04-09 13:05:34.000000,AGM announcements,AGM,Commerzbank Aktiengesellschaft,5b6e7203-ea7c-11e8-902f-2c44fd856d8c,DE000CBK1001,COMMERZBANK Aktiengesellschaft: Bekanntmachung...,de,de,Europe/Berlin,DE\nGerman\nShare\nPrint\nLanguage\nGerman\nCo...,https://www.eqs-news.com/news/agm-announcement...,2026-04-09 13:35:45.017670,"{""id"": ""e0dcf63f-e89e-4c13-b580-8eda9fc6910f_e..."
27,79d79323-8dde-4e66-b1c2-8fdfc75a3a93_en,2026-04-09 15:05:34.000000,2026-04-09 13:05:34.000000,AGM announcements,AGM,GSW Immobilien AG,5be20901-ea7c-11e8-902f-2c44fd856d8c,DE000GSW1111,GSW Immobilien AG: Bekanntmachung der Einberuf...,de,de,Europe/Berlin,DE\nGerman\nShare\nPrint\nLanguage\nGerman\nCo...,https://www.eqs-news.com/news/agm-announcement...,2026-04-09 13:35:45.017692,"{""id"": ""79d79323-8dde-4e66-b1c2-8fdfc75a3a93_e..."
28,0666f879-9467-4fef-bee5-bed7ee3bc723_en,2026-04-09 15:05:25.000000,2026-04-09 13:05:25.000000,AGM announcements,AGM,PUMA SE,5b71f4a1-ea7c-11e8-902f-2c44fd856d8c,DE0006969603,PUMA SE: Bekanntmachung der Einberufung zur Ha...,de,de,Europe/Berlin,DE\nGerman\nShare\nPrint\nLanguage\nGerman\nCo...,https://www.eqs-news.com/news/agm-announcement...,2026-04-09 13:35:45.017715,"{""id"": ""0666f879-9467-4fef-bee5-bed7ee3bc723_e..."
31,f500dc1c-4c81-4780-8593-e6ba9a7defac_en,2026-04-09 15:05:23.000000,2026-04-09 13:05:23.000000,AGM announcements,AGM,Vonovia SE,5bf8f933-ea7c-11e8-902f-2c44fd856d8c,DE000A1ML7J1,Vonovia SE: Bekanntmachung der Einberufung zur...,de,de,Europe/Berlin,DE\nGerman\nShare\nPrint\nLanguage\nGerman\nCo...,https://www.eqs-news.com/news/agm-announcement...,2026-04-09 13:35:45.017778,"{""id"": ""f500dc1c-4c81-4780-8593-e6ba9a7defac_e..."
30,069f4e3c-bbaf-4958-9fb2-3dfd90ee362f_en,2026-04-09 15:05:23.000000,2026-04-09 13:05:23.000000,AGM announcements,AGM,TAKKT AG,5b74ae71-ea7c-11e8-902f-2c44fd856d8c,DE0007446007,TAKKT AG: Bekanntmachung der Einberufung zur H...,de,de,Europe/Berlin,DE\nGerman\nShare\nPrint\nLanguage\nGerman\nCo...,https://www.eqs-news.com/news/agm-announcement...,2026-04-09 13:35:45.017757,"{""id"": ""069f4e3c-bbaf-4958-9fb2-3dfd90ee362f_e..."
29,3c61c314-1d3f-45f1-9c36-7452072b49ba_en,2026-04-09 15:05:23.000000,2026-04-09 13:05:23.000000,AGM announcements,AGM,LANXESS Aktiengesellschaft,5b7a92d0-ea7c-11e8-902f-2c44fd856d8c,DE0005470405,LANXESS Aktiengesellschaft: Bekanntmachung der...,de,de,Europe/Berlin,DE\nGerman\nShare\nPrint\nLanguage\nGerman\nCo...,https://www.eqs-news.com/news/agm-announcement...,2026-04-09 13:35:45.017736,"{""id"": ""3c61c314-1d3f-45f1-9c36-7452072b49ba_e..."
32,bdaf6a9d-0329-406f-8893-3b1e5abaef1c_en,2026-04-09 15:03:23.000000,2026-04-09 13:03:23.000000,Corporate,corporate,tZERO,fb727366-9ec7-11f0-8996-a5ce98c0c13b,noisin762917,tZERO Capital Partners Launches as Advisory Se...,en,en,Europe/Berlin,EN\nEnglish\nShare\nPrint\nLanguage\nEnglish\n...,https://www.eqs-news.com/news/corporate/tzero-...,2026-04-09 13:35:45.017800,"{""id"": ""bdaf6a9d-0329-406f-8893-3b1e5abaef1c_e..."
33,afd029c3-9fc3-4a5c-b997-6c44d6afe585_en,2026-04-09 14:59:41.000000,2026-04-09 12:59:41.000000,Corporate,corporate,Catalyst Crew Technologies Corp.,721c33e0-17f8-11f1-9d93-8d5af30165dd,US21116R3057,"Catalyst Crew Technologies Introduces NeuroAI,...",en,en,Europe/Berlin,EN\nEnglish\nShare\nPrint\nLanguage\nEnglish\n...,https://www.eqs-news.com/news/corporate/cataly...,2026-04-09 13:35:45.017821,"{""id"": ""afd029c3-9fc3-4a5c-b997-6c44d6afe585_e..."
34,f634b787-396c-4031-a9bb-5852fabf2416_en,2026-04-09 14:43:23.000000,2026-04-09 12:43:23.000000,Corporate,corporate,ADS-TEC Energy GmbH,242c7863-c917-1016-82b5-af7605d60f5f,IE000DU292E6,ADS-TEC Energy and Elanga bring ultra-fast cha...,en,"en,de",Europe/Berlin,EN\nEnglish\nGerman\nShare\nPrint\nLanguage\nE...,https://www.eqs-news.com/news/corporate/ads-te...,2026-04-09 13:35:45.017842,"{""id"": ""f634b787-396c-4031-a9bb-5852fabf2416_e..."
35,4b0e5539-41bd-402b-a111-8790471e2052_en,2026-04-09 14:34:52.000000,2026-04-09 12:34:52.000000,Corporate,corporate,"IMD Companies, Inc",d14d5312-8202-1014-a15b-7bf3d14827b4,US45928B1098,"iMD Companies, Inc. Begins Advanced Due Dilige...",en,en,Europe/Berlin,EN\nEnglish\nShare\nPrint\nLanguage\nEnglish\n...,https://www.eqs-news.com/news/corporate/imd-co...,2026-04-09 13:35:45.017863,"{""id"": ""4b0e5539-41bd-402b-a111-8790471e2052_e..."
36,7a9d6e7d-8a52-4eca-a8b0-7388f0348004_en,2026-04-09 14:30:03.000000,2026-04-09 12:30:03.000000,Corporate,corporate,Carvolix,f93de5de-dd13-1015-9b01-c20717257b19,FR0013333077,Carvolix verstärkt seinen Aufsichtsrat sowie s...,de,de,Europe/Berlin,DE\nGerman\nShare\nPrint\nLanguage\nGerman\nCo...,https://www.eqs-news.com/news/corporate/carvol...,2026-04-09 13:35:45.017884,"{""id"": ""7a9d6e7d-8a52-4eca-a8b0-7388f0348004_e..."
37,c47a295e-f49c-4d65-afaa-0fac14278a2d_en,2026-04-09 14:26:04.000000,2026-04-09 12:26:04.000000,Ad-hoc,adhoc,Heidelberg Pharma AG,5b769380-ea7c-11e8-902f-2c44fd856d8c,DE000A11QVV0,Heidelberg Pharma AG: Heidelberg Pharma Determ...,en,"de,en",Europe/Berlin,EN\nGerman\nEnglish\nShare\nPrint\nLanguage\nG...,https://www.eqs-news.com/news/ad-hoc/heidelber...,2026-04-09 13:35:45.017904,"{""id"": ""c47a295e-f49c-4d65-afaa-0fac14278a2d_e..."
38,45364751-5e8a-4c74-b4fe-aca76f0acc40_en,2026-04-09 14:24:33.000000,2026-04-09 12:24:33.000000,Voting rights,PVR,NORMA Group SE,5bd7dea8-ea7c-11e8-902f-2c44fd856d8c,DE000A1H8BV3,"The Goldman Sachs Group, Inc., Wilmington, DE,...",en,"de,en",Europe/Berlin,EN\nGerman\nEnglish\nShare\nPrint\nLanguage\nG...,https://www.eqs-news.com/news/voting-rights/th...,2026-04-09 13:35:45.017925,"{""id"": ""45364751-5e8a-4c74-b4fe-aca76f0acc40_e..."
39,d0619430-dfcf-496a-ba23-c86245474e49_en,2026-04-09 13:15:25.000000,2026-04-09 12:15:25.000000,UK Regulatory,UK-Regulatory,Apex Fundrock Limited,5c4ad19f-ea7c-11e8-902f-2c44fd856d8c,noisin035209,Form 8.3 - Gamma Communications PLC,en,en,Europe/London,EN\nEnglish\nShare\nPrint\nLanguage\nEnglish\n...,https://www.eqs-news.com/news/uk-regulatory/fo...,2026-04-09 13:35:45.017945,"{""id"": ""d0619430-dfcf-496a-ba23-c86245474e49_e..."

In [6]:
from IPython.display import HTML

HTML(df[['headline']].to_html(max_rows=1000))

In [ ]:
display(df['headline'])